#!/bin/bash

title="$1"
shift

echo "<p><hr>"
echo "<p>"
echo "<span class="boldmaroon">${title}</span>"

cat "$@" | sed -e 's/--/\&mdash;/g' -e 's/^/<br>/' -e "s/'/\&rsquo;/"

#git add index.html
#git commit -m $title
#synctool -r u58051762@home321765456.1and1-data.host reltoremote
